### ISSUE TITLE
[AFADMIN_CLIENT] registration 

### ISSUE THREAD

**Issue by pnoulis** [pnoulis/agent_factory#1]
1. Form fields text needs to be uppercase.
2. The pairing process must be initiated after user input and not by default.
3. Only one player must be in the wristband pairing mode at any one time.
4. Alert when a player is already registered. Should they be de-registered?

**Comment by gregorykolasis** [comment]
@pnoulis Waiting for the changes for this issue. This is your first priority

**Comment by pnoulis** [comment]
Done
